config/routes.rb
Rails.application.routes.draw do

  devise_for :users

   root 'home#index'

      resources :blogs,:packages,:hotels,:package_types
      
      resources :blogs do
        resources :comments,:only=>[:create,:destroy]
      end
      

      namespace :admin do
        resources :hotels, :blogs,:packages,:package_types,:users
      end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	#def to_param
    #	"#{id} #{name}".parameterize
  	#end

	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	has_many :comments,dependent: :destroy
	has_many :comments,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:description , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:address , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	mount_uploader :avatar, AvatarUploader
end

app/models/package.rb
class Package < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
	
	has_many :package_types, dependent: :destroy

	validates :name,:destination , presence: true
	validates :name,length: { in: 4..20 }
end

app/models/package_type.rb
class PackageType < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :transport, use: [:slugged,:finders]
	
	has_many :images, as: :imageable,dependent: :destroy
	belongs_to :package
	accepts_nested_attributes_for :images

	validates :price,:transport, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
   	validates :name, presence: true,length: { in: 4..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def current_admin
      authenticate_user!
      redirect_to root_url unless current_user
      unless current_user.is_admin?
        redirect_to root_url
      end
    end

  	def after_sign_in_path_for(resource)
  		if resource.is_admin?
			  admin_hotels_path
		  else
			  root_path
		  end
  	end

  	def after_sign_up_path_for(resource) 
  		root_path
	end 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  	def index
  		@blogs = Blog.all
  	end

  	def show
  		@blog = Blog.find(params[:id])
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
  	before_action :set_comment, only: [:destroy]
  	#before_action :find_forum_and_topic

  	def create

    	@comment = Comment.new(comment_params)
    	respond_to do |format|
	      	if @comment.save 
            @blog = @comment.blog       
	        	format.js {}        
	      	else        
	        	format.js{          
	          		flash[:error] = @comment.errors.full_messages.map{|x| "<span>#{x}</span>" }.join(' ')                  
	        	} 
	      	end      
    	end
  	end

	def destroy
      @blog = @comment.blog 
	    @comment.destroy
	    respond_to do |format|      
	      format.js { 
	        flash[:notice] = 'Comment was successfully deleted.'
	      }
	    end
	end

  	private

    def set_comment
      	@comment = Comment.find(params[:id])
      	rescue ActiveRecord::RecordNotFound
        flash[:error] = "Record not found ..!!!"
        redirect_to root_url
    end

     def comment_params
      params.require(:comment).permit(:description, :user_id, :blog_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  	def index
  		@hotels = Hotel.all
  	end

  	def show
  		@hotel = Hotel.find(params[:id])
  	end
end

app/controllers/package_types_controller.rb
class PackageTypesController < ApplicationController
  def index
  		@package_types = PackageType.all
  	end

  	def show
  		@package_type = PackageType.find(params[:id])
  	end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  	
  	def index
  		@packages = Package.all
  	end

  	def show
  		@package = Package.find(params[:id])
  	end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/package_types_helper.rb
module PackageTypesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/comments/_blog_comments.html.erb
<div class="well well-small">
<% if blog.present? %>
    
    <div class="comment_section">
        <h3>Comments</h3>
        <% if blog.comments.count > 0 %>   
            <% index = 0 %>
            <% blog.comments.each do |comment| %>
               <div>
                   <p class="posted_by">
                        <%=  index+=1 %>.&nbsp;
                        Posted By <%= comment.created_at.strftime("%b %d '%y at %H:%M") %> 
                        <%# debug comment %>
                        <% if current_user.id == comment.user_id || current_user.is_admin? %>
                              <span class="comment_close">
                                <%= link_to image_tag("75.jpg"),blog_comment_path(@blog,comment),
                              :method => :delete,
                              :remote => true,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }
                              %>                    
                            </span>                 
                        <% end %>
                    </p>
                    <p><%= comment.description.html_safe %></p>
                </div>
               <hr>
            <% end %>        
        <% else %>
            <p>Be your first comment ..!!!</p>
        <% end %>
    </div>

    <% if current_user %>        
        <div class="leave_comment_section">
             <%= form_for ([blog,Comment.new]),remote: true do |f| %>        
                <%= f.hidden_field :blog_id,value: blog[:id] %>
                <%= f.hidden_field :user_id,value: current_user[:id] %>            
                <div class="form_row">                             
                    <%= f.text_area :description,cols: 100,rows: 3, required: true,:placeholder=>"Enter your comment....." %>
                </div>
                <%= f.submit "Submit",class: "btn btn-primary butt", id: "ajaxSubmit" %>            
            <% end %>              
        </div>  
    <% else %>
        <div class="leave_comment_section">
            <%= link_to "Login to give comment", new_user_session_path %>
        </div>
    <% end %>

<% end %> 
</div>

<style>
input, textarea, .uneditable-input{
    width: auto;
}
</style>

app/views/comments/create.js.erb
$('#comment_section').html("<%= escape_javascript(render :partial => 'comments/blog_comments', :locals => { :blog => @blog } ) %>");

app/views/comments/destroy.js.erb
$('#comment_section').html("<%= escape_javascript(render :partial => 'comments/blog_comments', :locals => { :blog => @blog } ) %>");