config/routes.rb
Rails.application.routes.draw do

  devise_for :users

   root 'home#index'

      resources :blogs,:packages,:hotels,:package_types
      
      resources :blogs do
        resources :comments,:only=>[:create,:destroy]
      end
      

      namespace :admin do
        resources :hotels, :blogs,:packages,:package_types,:users
      end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	#def to_param
    #	"#{id} #{name}".parameterize
  	#end

	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	has_many :comments,dependent: :destroy
	has_many :comments,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:description , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:address , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	mount_uploader :avatar, AvatarUploader
end

app/models/package.rb
class Package < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
	
	has_many :package_types, dependent: :destroy

	validates :name,:destination , presence: true
	validates :name,length: { in: 4..20 }
end

app/models/package_type.rb
class PackageType < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :transport, use: [:slugged,:finders]
	
	has_many :images, as: :imageable,dependent: :destroy
	belongs_to :package
	accepts_nested_attributes_for :images

	validates :price,:transport, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
   	validates :name, presence: true,length: { in: 4..20 }
end

app/controllers/admin/package_types_controller.rb
class Admin::PackageTypesController < ApplicationController
  before_filter :current_admin
	before_action :set_admin_package_type, only: [:show, :edit, :update, :destroy]
  layout "admin"
  def index
    @package_types = PackageType.all
  end

  def show
  end

  def new
    @package_type = PackageType.new
  end

  def edit
  end

  	def create
    	@package_type = PackageType.new(package_type_params)

   		if @package_type.save
	        flash[:notice] = 'Package type was successfully created.' 
    	    redirect_to admin_package_types_url
      	else
        	flash[:error] = 'package type was not created'
        	render "new"
      	end
    end

  	def update
        if @package_type.update(package_type_params)
        	flash[:notice] = 'Package type was successfully updated.' 
        	redirect_to admin_package_types_url
      	else
        	flash[:error] = "Package Type not updated"
        	render "edit"
      end
    end


  	def destroy
    	@package_type.destroy
    	respond_to do |format|
      		format.html { redirect_to admin_package_types_url, notice: 'Package type was successfully destroyed.' }
      		format.json { head :no_content }
    	end	
  	end

  	private

    def set_admin_package_type
      @package_type = PackageType.find(params[:id])
    end


    def package_type_params
      params.require(:package_type).permit(:transport, :price, :days, :nights, :package_id,images_attributes: [:id,:avatar,:imageable_id,:imageable_type,:_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def current_admin
      authenticate_user!
      redirect_to root_url unless current_user
      unless current_user.is_admin?
        redirect_to root_url
      end
    end

  	def after_sign_in_path_for(resource)
  		if resource.is_admin?
			  admin_hotels_path
		  else
			  root_path
		  end
  	end

  	def after_sign_up_path_for(resource) 
  		root_path
	end 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  	def index
  		@blogs = Blog.all
  	end

  	def show
  		@blog = Blog.find(params[:id])
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
  	before_action :set_comment, only: [:destroy]
  	#before_action :find_forum_and_topic

  	def create

    	@comment = Comment.new(comment_params)
    	respond_to do |format|
	      	if @comment.save 
            @blog = @comment.blog       
	        	format.js {}        
	      	else        
	        	format.js{          
	          		flash[:error] = @comment.errors.full_messages.map{|x| "<span>#{x}</span>" }.join(' ')                  
	        	} 
	      	end      
    	end
  	end

	def destroy
      @blog = @comment.blog 
	    @comment.destroy
	    respond_to do |format|      
	      format.js { 
	        flash[:notice] = 'Comment was successfully deleted.'
	      }
	    end
	end

  	private

    def set_comment
      	@comment = Comment.find(params[:id])
      	rescue ActiveRecord::RecordNotFound
        flash[:error] = "Record not found ..!!!"
        redirect_to root_url
    end

     def comment_params
      params.require(:comment).permit(:description, :user_id, :blog_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  	def index
  		@hotels = Hotel.all
  	end

  	def show
  		@hotel = Hotel.find(params[:id])
  	end
end

app/controllers/package_types_controller.rb
class PackageTypesController < ApplicationController
  def index
  		@package_types = PackageType.all
  	end

  	def show
  		@package_type = PackageType.find(params[:id])
  	end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  	
  	def index
  		@packages = Package.all
  	end

  	def show
  		@package = Package.find(params[:id])
  	end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/package_types_helper.rb
module Admin::PackageTypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/package_types_helper.rb
module PackageTypesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/admin/package_types/_form.html.erb
<div class='bodyCnt'>
  <div class='wraper'>
    <div class='' id='inner-main'>
      <div class='subNavCnt'>
        <h1>New PackageType</h1>
        <div class='moreLinks'>
          <ul>
            <li>
              <a href="/service_admin" class="btn"><%= link_to "Back", admin_package_types_path %></a>
            </li>
          </ul>
        </div>
        <div class='clear'></div>
      </div>

      <div class='wraper'>
        <%= nested_form_for([:admin,@package_type],:html=>{:multipart =>true} ) do |f| %>
          <div class='sectionCnt'>
            <h2>
            PackageType
            </h2>
            <div class='formLayout'>
              
              <div class="row">
                <label for="service_title"><%= f.label :package_id %></label>
                <div class='inputCnt'>
                  <%= f.select :package_id, Package.all.map {|x| [x.name,x.id]}, prompt: "select category" %>
                </div>
                <div class='clear'></div>
              </div>

              <div class='row'>
                <label for="service_title"><%= f.label :transport %></label>
                <div class='inputCnt'>
                  <%= f.select :transport, ['Bus','Train','Airplane'] %>
                </div>
                <div class='clear'></div>
              </div>

              <div class='row'>
                <label for="service_description"><%= f.label :price %></label>
                <div class='inputCnt'>
                  <%= f.text_field :price %>
                </div>
                <div class='clear'></div>
              </div>

              <div class='row'>
                <label for="service_description"><%= f.label :days %></label>
                <div class='inputCnt'>
                  <%= f.number_field :days %>
                </div>
                <div class='clear'></div>
              </div>

              <div class='row'>
                <label for="service_description"><%= f.label :nights %></label>
                <div class='inputCnt'>
                  <%= f.number_field :nights %>
                </div>
                <div class='clear'></div>
              </div>

              <div class="row">
                <%= f.fields_for :images do |image| %>
                  <p>
                    <%= image.label :image ,:style => "margin-left: 10px;" %>
                    <%= image.file_field :avatar%>
                    <%= image.link_to_remove "Remove image" ,:class => "remove_link",:style=>"margin-left: 110px;"%>
                  </p>
                  <br/>
                <% end %>
                <p>
                  <%= f.link_to_add "Add image", :images , :class => "btn adminAddPhoto" %>
                </p>
              </div>
              <div class='clear'></div>
              <hr class='seprator'>

              <div class='actions'>
                <%= f.submit %>
              </div>
            </div>
          </div>
        <% end %>
        <style>
          .message{color: red;display: block;padding-left: 144px;}
        </style>
      </div>
      <script>
        var topNavPageId = 0
      </script>
    </div>
  </div>
  <div class='clear'></div>
</div>
<div class='clear'></div>
</div>

app/views/admin/package_types/_form.html.haml
.bodyCnt
  .wraper
    #inner-main
      .subNavCnt
        %h1 New PackageType
        .moreLinks
          %ul
            %li
              %a.btn{:href => "/service_admin"}= link_to "Back", admin_package_types_path
        .clear
      .wraper
        = nested_form_for([:admin,@package_type],:html=>{:multipart =>true} ) do |f|
          .sectionCnt
            %h2
              PackageType
            .formLayout
              .row
                %label{:for => "service_title"}= f.label :package_id
                .inputCnt
                  = f.select :package_id, Package.all.map {|x| [x.name,x.id]}, prompt: "select category"
                .clear
              .row
                %label{:for => "service_title"}= f.label :transport
                .inputCnt
                  = f.select :transport, ['Bus','Train','Airplane']
                .clear
              .row
                %label{:for => "service_description"}= f.label :price
                .inputCnt
                  = f.text_field :price
                .clear
              .row
                %label{:for => "service_description"}= f.label :days
                .inputCnt
                  = f.number_field :days
                .clear
              .row
                %label{:for => "service_description"}= f.label :nights
                .inputCnt
                  = f.number_field :nights
                .clear
              .row
                = f.fields_for :images do |image|
                  %p
                    = image.label :image ,:style => "margin-left: 10px;"
                    = image.file_field :avatar
                    = image.link_to_remove "Remove image" ,:class => "remove_link",:style=>"margin-left: 110px;"
                  %br/
                %p
                  = f.link_to_add "Add image", :images , :class => "btn adminAddPhoto"
              .clear
              %hr.seprator/
              .actions
                = f.submit
        :css
          .message{color: red;display: block;padding-left: 144px;}
      :javascript
        var topNavPageId = 0
  .clear
.clear

app/views/admin/package_types/edit.html.erb
<%= render 'form' %>

app/views/admin/package_types/edit.html.haml
= render 'form'

app/views/admin/package_types/index.html.erb
<div class='bodyCnt'>
    <div class='wraper'>
      <div class='' id='inner-main'>
        <div class='subNavCnt'>
          <h1>PackageTypes</h1>
          <div class='moreLinks'>
            <ul>
              <li>
                <a href="/services/new" class="btn"><%= link_to "Add New PackageType", new_admin_package_type_path %></a>
              </li>
            </ul>
          </div>
          <div class='clear'></div>
        </div>
        <table class='cmsTable'>
          <tr>
            <th>Transport</th>
            <th>Price</th>
            <th>Days</th>
            <th>Nights</th>
            <th>Package</th>
            <th colspan="3"></th>
          </tr>
          <% @package_types.each do |package_type| %>
            <tr>
              <td><%= package_type.transport %></td>
              <td><%= package_type.price %></td>
              <td><%= package_type.days %></td>
              <td><%= package_type.nights %></td>
              <td><%= package_type.package_id %></td>
              <td><%= link_to 'Edit', edit_admin_package_type_path(package_type) %></td>
              <td><%= link_to 'Destroy', admin_package_type_path(package_type), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </table>
        <br>
        <br>
        <script>
          var topNavPageId = 0
        </script>
      </div>
    </div>
    <div class='clear'></div>
</div>
<div class='clear'></div>

app/views/admin/package_types/index.html.haml
.bodyCnt
  .wraper
    #inner-main
      .subNavCnt
        %h1 PackageTypes
        .moreLinks
          %ul
            %li
              %a.btn{:href => "/services/new"}= link_to "Add New PackageType", new_admin_package_type_path
        .clear
      %table.cmsTable
        %tr
          %th Transport
          %th Price
          %th Days
          %th Nights
          %th Package
          %th{:colspan => "3"}
        - @package_types.each do |package_type|
          %tr
            %td= package_type.transport
            %td= package_type.price
            %td= package_type.days
            %td= package_type.nights
            %td= package_type.package_id
            %td= link_to 'Edit', edit_admin_package_type_path(package_type)
            %td= link_to 'Destroy', admin_package_type_path(package_type), method: :delete, data: { confirm: 'Are you sure?' }
      %br/
      %br/
      :javascript
        var topNavPageId = 0
  .clear
.clear

app/views/admin/package_types/new.html.erb
<%= render 'form' %>

app/views/admin/package_types/new.html.haml
= render 'form' 

app/views/admin/package_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transport:</strong>
  <%= @package_type.transport %>
</p>

<p>
  <strong>Price:</strong>
  <%= @package_type.price %>
</p>

<p>
  <strong>Days:</strong>
  <%= @package_type.days %>
</p>

<p>
  <strong>Nights:</strong>
  <%= @package_type.nights %>
</p>

<p>
  <strong>Photo:</strong>
  <% if @package_type.images.present? %>
    <% @package_type.images.each do |image| %>
      <%= image_tag(image.avatar_url,size: "80x46") %>
    <% end %>
  <% else %>
    <p>images are not present</p>
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_package_type_path(@package_type) %> |
<%= link_to 'Back', admin_package_types_path %>

app/views/package_types/index.html.erb
<div class='bodyCnt'>
    <div class='wraper'>
      <div class='' id='inner-main'>
        <div class='subNavCnt'>
          <h1>PackageTypes</h1>
          <div class='clear'></div>
        </div>
        <table class='cmsTable'>
          <tr>
            <th>Transport</th>
            <th>Price</th>
            <th>Days</th>
            <th>Nights</th>
            <th>Package</th>
            <th colspan="3"></th>
          </tr>
          <% @package_types.each do |package_type| %>
            <tr>
              <td><%= package_type.transport %></td>
              <td><%= package_type.price %></td>
              <td><%= package_type.days %></td>
              <td><%= package_type.nights %></td>
              <td><%= package_type.package_id %></td>
              <td><%= link_to 'Show', package_type_path(package_type) %></td>
            </tr>
          <% end %>
        </table>
        <br>
        <br>
        <script>
          var topNavPageId = 0
        </script>
      </div>
    </div>
    <div class='clear'></div>
</div>
<div class='clear'></div>

app/views/package_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transport:</strong>
  <%= @package_type.transport %>
</p>

<p>
  <strong>Price:</strong>
  <%= @package_type.price %>
</p>

<p>
  <strong>Days:</strong>
  <%= @package_type.days %>
</p>

<p>
  <strong>Nights:</strong>
  <%= @package_type.nights %>
</p>

<p>
  <strong>Photo:</strong>
  <% if @package_type.images.present? %>
    <% @package_type.images.each do |image| %>
      <%= image_tag(image.avatar_url,size: "80x46") %>
    <% end %>
  <% else %>
    <p>images are not present</p>
  <% end %>
</p>

<%= link_to 'Back', package_types_path %>