config/routes.rb
Rails.application.routes.draw do

  devise_for :users

   root 'home#index'

      resources :blogs,:packages,:hotels,:package_types
      
      resources :blogs do
        resources :comments,:only=>[:create,:destroy]
      end
      

      namespace :admin do
        resources :hotels, :blogs,:packages,:package_types,:users
      end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	#def to_param
    #	"#{id} #{name}".parameterize
  	#end

	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	has_many :comments,dependent: :destroy
	has_many :comments,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:description , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:address , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	mount_uploader :avatar, AvatarUploader
end

app/models/package.rb
class Package < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
	
	has_many :package_types, dependent: :destroy

	validates :name,:destination , presence: true
	validates :name,length: { in: 4..20 }
end

app/models/package_type.rb
class PackageType < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :transport, use: [:slugged,:finders]
	
	has_many :images, as: :imageable,dependent: :destroy
	belongs_to :package
	accepts_nested_attributes_for :images

	validates :price,:transport, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
   	validates :name, presence: true,length: { in: 4..20 }
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
  before_filter :current_admin
	before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  layout "admin"

 	def index
   	@hotels = Hotel.all
 	end

	def show
	end

	def new
    	@hotel = Hotel.new
  	end

  	def edit
  	end


  	def create
    	@hotel = Hotel.new(hotel_params)
      	if @hotel.save
			#render :text=>params and return false
	        redirect_to admin_hotels_url
     	else
	        render "new"
      	end
  	end


  	def update
	    if @hotel.update(hotel_params)
	        redirect_to admin_hotels_url
	    else
	        render "edit"
	    end
  	end

	def destroy
	    @hotel.destroy
	    respond_to do |format|
	      	format.html { redirect_to admin_hotels_url, notice: 'Hotel was successfully destroyed.' }
	      	format.json { head :no_content }
	    end
	end

  private

    def set_hotel
      	@hotel = Hotel.find(params[:id])
    end


    def hotel_params
      	params.require(:hotel).permit(:name, :address, images_attributes: [:id,:avatar,:imageable_id,:imageable_type,:_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def current_admin
      authenticate_user!
      redirect_to root_url unless current_user
      unless current_user.is_admin?
        redirect_to root_url
      end
    end

  	def after_sign_in_path_for(resource)
  		if resource.is_admin?
			  admin_hotels_path
		  else
			  root_path
		  end
  	end

  	def after_sign_up_path_for(resource) 
  		root_path
	end 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  	def index
  		@blogs = Blog.all
  	end

  	def show
  		@blog = Blog.find(params[:id])
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
  	before_action :set_comment, only: [:destroy]
  	#before_action :find_forum_and_topic

  	def create

    	@comment = Comment.new(comment_params)
    	respond_to do |format|
	      	if @comment.save 
            @blog = @comment.blog       
	        	format.js {}        
	      	else        
	        	format.js{          
	          		flash[:error] = @comment.errors.full_messages.map{|x| "<span>#{x}</span>" }.join(' ')                  
	        	} 
	      	end      
    	end
  	end

	def destroy
      @blog = @comment.blog 
	    @comment.destroy
	    respond_to do |format|      
	      format.js { 
	        flash[:notice] = 'Comment was successfully deleted.'
	      }
	    end
	end

  	private

    def set_comment
      	@comment = Comment.find(params[:id])
      	rescue ActiveRecord::RecordNotFound
        flash[:error] = "Record not found ..!!!"
        redirect_to root_url
    end

     def comment_params
      params.require(:comment).permit(:description, :user_id, :blog_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  	def index
  		@hotels = Hotel.all
  	end

  	def show
  		@hotel = Hotel.find(params[:id])
  	end
end

app/controllers/package_types_controller.rb
class PackageTypesController < ApplicationController
  def index
  		@package_types = PackageType.all
  	end

  	def show
  		@package_type = PackageType.find(params[:id])
  	end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  	
  	def index
  		@packages = Package.all
  	end

  	def show
  		@package = Package.find(params[:id])
  	end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/package_types_helper.rb
module PackageTypesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/admin/hotels/_form.html.erb
<div class='bodyCnt'>
  <div class='wraper'>
    <div class='' id='inner-main'>
      <div class='subNavCnt'>
        <h1>New Hotel</h1>
        <div class='moreLinks'>
          <ul>
            <li>
              <a href="/service_admin" class="btn"><%= link_to "Back", admin_hotels_path %></a>
            </li>
          </ul>
        </div>
        <div class='clear'></div>
      </div>

      <div class='wraper'>
        <%= nested_form_for([:admin,@hotel],:html=>{:multipart =>true} ) do |f| %>
          <div class='sectionCnt'>
            <h2>
            Hotel
            </h2>
            <div class='formLayout'>
              
              <div class='row'>
                <label for="service_title"><%= f.label :name %></label>
                <div class='inputCnt'>
                  <%= f.text_field :name %>
                </div>
                <div class='clear'></div>
              </div>

              <div class='row'>
                <label for="service_description"><%= f.label :address %></label>
                <div class='inputCnt'>
                  <%= f.text_area :address %>
                </div>
                <div class='clear'></div>
              </div>

              <div class="row">
                <%= f.fields_for :images do |image| %>
                  <p>
                    <%= image.label :image ,:style => "margin-left: 10px;" %>
                    <%= image.file_field :avatar%>
                    <%= image.link_to_remove "Remove image" ,:class => "remove_link",:style=>"margin-left: 110px;"%>
                  </p>
                  <br/>
                <% end %>
                <p>
                  <%= f.link_to_add "Add image", :images , :class => "btn adminAddPhoto" %>
                </p>
              </div>
              <div class='clear'></div>
              <hr class='seprator'>

              <div class='actions'>
                <%= f.submit %>
              </div>
            </div>
          </div>
        <% end %>
        <style>
          .message{color: red;display: block;padding-left: 144px;}
        </style>
      </div>
      <script>
        var topNavPageId = 0
      </script>
    </div>
  </div>
  <div class='clear'></div>
</div>
<div class='clear'></div>
</div>

app/views/admin/hotels/_form.html.haml
.bodyCnt
  .wraper
    #inner-main
      .subNavCnt
        %h1 New Hotel
        .moreLinks
          %ul
            %li
              %a.btn{:href => "/service_admin"}= link_to "Back", admin_hotels_path
        .clear
      .wraper
        = nested_form_for([:admin,@hotel],:html=>{:multipart =>true} ) do |f|
          .sectionCnt
            %h2
              Hotel
            .formLayout
              .row
                %label{:for => "service_title"}= f.label :name
                .inputCnt
                  = f.text_field :name
                .clear
              .row
                %label{:for => "service_description"}= f.label :address
                .inputCnt
                  = f.text_area :address
                .clear
              .row
                = f.fields_for :images do |image|
                  %p
                    = image.label :image ,:style => "margin-left: 10px;"
                    = image.file_field :avatar
                    = image.link_to_remove "Remove image" ,:class => "remove_link",:style=>"margin-left: 110px;"
                  %br/
                %p
                  = f.link_to_add "Add image", :images , :class => "btn adminAddPhoto"
              .clear
              %hr.seprator/
              .actions
                = f.submit
        :css
          .message{color: red;display: block;padding-left: 144px;}
      :javascript
        var topNavPageId = 0
  .clear
.clear

app/views/admin/hotels/edit.html.erb
<%= render 'form' %>

app/views/admin/hotels/edit.html.haml
= render 'form'

app/views/admin/hotels/index.html.erb
<div class='bodyCnt'>
    <div class='wraper'>
      <div class='' id='inner-main'>
        <div class='subNavCnt'>
          <h1>Hotels</h1>
          <div class='moreLinks'>
            <ul>
              <li>
                <a href="/services/new" class="btn"><%= link_to "Add New Hotel", new_admin_hotel_path %></a>
              </li>
            </ul>
          </div>
          <div class='clear'></div>
        </div>
        <table class='cmsTable'>
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th colspan="3"></th>
          </tr>
          <% @hotels.each do |hotel| %>
          <tr>
            <td><%= hotel.name %></td>
            <td><%= hotel.address %></td>
            <td><%= link_to 'Edit', edit_admin_hotel_path(hotel) %></td>
            <td><%= link_to 'Destroy', admin_hotel_path(hotel), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </table>
        <br>
        <br>
        <script>
          var topNavPageId = 0
        </script>
      </div>
    </div>
    <div class='clear'></div>
  </div>
  <div class='clear'></div>

app/views/admin/hotels/index.html.haml
.bodyCnt
  .wraper
    #inner-main
      .subNavCnt
        %h1 Hotels
        .moreLinks
          %ul
            %li
              %a.btn{:href => "/services/new"}= link_to "Add New Hotel", new_admin_hotel_path
        .clear
      %table.cmsTable
        %tr
          %th Name
          %th Address
          %th{:colspan => "3"}
        - @hotels.each do |hotel|
          %tr
            %td= hotel.name
            %td= hotel.address
            %td= link_to 'Edit', edit_admin_hotel_path(hotel)
            %td= link_to 'Destroy', admin_hotel_path(hotel), method: :delete, data: { confirm: 'Are you sure?' }
      %br/
      %br/
      :javascript
        var topNavPageId = 0
  .clear
.clear

app/views/admin/hotels/new.html.erb
<%= render 'form' %>

app/views/admin/hotels/new.html.haml
= render 'form'

app/views/admin/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Photo:</strong>
  <% if @hotel.images.present? %>
  	<% @hotel.images.each do |image| %>
  		<%= image_tag(image.avatar_url,size: "80x46") %>
  	<% end %>
  <% else %>
  	<p>images are not present</p>
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_hotel_path(@hotel) %> |
<%= link_to 'Back', admin_hotels_path %>

app/views/hotels/index.html.erb
<div class='bodyCnt'>
    <div class='wraper'>
      <div class='' id='inner-main'>
        <div class='subNavCnt'>
          <h1>Hotels</h1>
          <div class='clear'></div>
        </div>
        <table class='cmsTable'>
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th colspan="3"></th>
          </tr>
          <% @hotels.each do |hotel| %>
          <tr>
            <td><%= hotel.name %></td>
            <td><%= hotel.address %></td>
            <td><%= link_to 'Show', hotel_path(hotel) %></td>
          </tr>
          <% end %>
        </table>
        <br>
        <br>
        <script>
          var topNavPageId = 0
        </script>
      </div>
    </div>
    <div class='clear'></div>
  </div>
  <div class='clear'></div>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Photo:</strong>
  <% if @hotel.images.present? %>
  	<% @hotel.images.each do |image| %>
  		<%= image_tag(image.avatar_url,size: "80x46") %>
  	<% end %>
  <% else %>
  	<p>images are not present</p>
  <% end %>
</p>

<%= link_to 'Back', hotels_path %>