config/routes.rb
Rails.application.routes.draw do

  devise_for :users

   root 'home#index'

      resources :blogs,:packages,:hotels,:package_types
      
      resources :blogs do
        resources :comments,:only=>[:create,:destroy]
      end
      

      namespace :admin do
        resources :hotels, :blogs,:packages,:package_types,:users
      end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	#def to_param
    #	"#{id} #{name}".parameterize
  	#end

	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	has_many :comments,dependent: :destroy
	has_many :comments,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:description , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
  	
	has_many :images, as: :imageable,dependent: :destroy
	accepts_nested_attributes_for :images

	validates :name,:address , presence: true
	validates :name,length: { in: 3..20 }
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	mount_uploader :avatar, AvatarUploader
end

app/models/package.rb
class Package < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: [:slugged,:finders]
	
	has_many :package_types, dependent: :destroy

	validates :name,:destination , presence: true
	validates :name,length: { in: 4..20 }
end

app/models/package_type.rb
class PackageType < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :transport, use: [:slugged,:finders]
	
	has_many :images, as: :imageable,dependent: :destroy
	belongs_to :package
	accepts_nested_attributes_for :images

	validates :price,:transport, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
   	validates :name, presence: true,length: { in: 4..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def current_admin
      authenticate_user!
      redirect_to root_url unless current_user
      unless current_user.is_admin?
        redirect_to root_url
      end
    end

  	def after_sign_in_path_for(resource)
  		if resource.is_admin?
			  admin_hotels_path
		  else
			  root_path
		  end
  	end

  	def after_sign_up_path_for(resource) 
  		root_path
	end 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  	def index
  		@blogs = Blog.all
  	end

  	def show
  		@blog = Blog.find(params[:id])
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
  	before_action :set_comment, only: [:destroy]
  	#before_action :find_forum_and_topic

  	def create

    	@comment = Comment.new(comment_params)
    	respond_to do |format|
	      	if @comment.save 
            @blog = @comment.blog       
	        	format.js {}        
	      	else        
	        	format.js{          
	          		flash[:error] = @comment.errors.full_messages.map{|x| "<span>#{x}</span>" }.join(' ')                  
	        	} 
	      	end      
    	end
  	end

	def destroy
      @blog = @comment.blog 
	    @comment.destroy
	    respond_to do |format|      
	      format.js { 
	        flash[:notice] = 'Comment was successfully deleted.'
	      }
	    end
	end

  	private

    def set_comment
      	@comment = Comment.find(params[:id])
      	rescue ActiveRecord::RecordNotFound
        flash[:error] = "Record not found ..!!!"
        redirect_to root_url
    end

     def comment_params
      params.require(:comment).permit(:description, :user_id, :blog_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  	def index
  		@hotels = Hotel.all
  	end

  	def show
  		@hotel = Hotel.find(params[:id])
  	end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  	
  	def index
  		@packages = Package.all
  	end

  	def show
  		@package = Package.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/package_types_helper.rb
module PackageTypesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="cms-container">
  		<div class="header">
    		<div class="wraper">
      			<div class="adminInfo">
			        <% if user_signed_in? %>
			          Logged in as:<%= current_user.email %> || <%= link_to 'Logout', destroy_user_session_path ,:method => :delete,:style=>"color:#fff" %>
			        <% end %>
      			</div>
      			<div class="logo">
			        <a href="/">
			          <%= image_tag("75.jpg", size: "57x65") %>
			        </a>
			    </div>
			    <div class="clear"></div>
    		</div>
  		</div>
	</div>

	<header class='mainNav boxLink'>
	    <section class='wraper'>
	    	<nav class='topNav'>
	    		<ul class='mainMenu'>
	    			<li>
				    	<%= link_to "Users", admin_users_path %>
				    </li>
				    <li>
				    	<%= link_to "Hotels", admin_hotels_path %>
				    </li>
				    <li>
				    	<%= link_to "Packages", admin_packages_path %>
				    </li>
				    <li>
				    	<%= link_to "PackageTypes", admin_package_types_path %>
				    </li>
				    <li>
				    	<%= link_to "Blogs", admin_blogs_path %>
				    </li>
				</ul>
				<div class='clear'></div>
	    	</nav>
	    </section>
	</header>
	<div class='clear'></div>
	<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

			        <% if user_signed_in? %>
			          Logged in as:<%= current_user.email %> || <%= link_to 'Logout', destroy_user_session_path ,:method => :delete,:style=>"color:#fff" %>
			        <% end %>
      			

<%= yield %>

</body>
</html>

app/views/shared/header_content.html.erb
<div id='cms-container'>
    <div class='header'>
      <div class='wraper'>
        <div class='adminInfo'>
          Logged in as:
          admin@liftandshift.com
          |
          <a href="/users/sign_out" data-method="delete" rel="nofollow" style="color:#fff">Logout</a>
        </div>
        <div class='logo'>
          <a href='/'>
            <img alt="Logo" src="/assets/logo-528ef52a12175a2b71e8894f5fdae496.jpg" style="width:100%" />
          </a>
        </div>
      <div class='clear'></div>
    </div>
  </div>

  <header class='mainNav boxLink'>
    <section class='wraper'>
    <nav class='topNav'>
    <ul class='mainMenu'>
    <li>
    <a href="/slider_admin" class="">Home Page Slider</a>
    </li>
    <li>
    <a href="/home_banners" class="">Home Page</a>
    </li>
    <li>
    <a href="/banners" class="">Banners</a>
    </li>
    <li>
    <a href="/service_admin" class="active">Service</a>
    </li>
    <li>
    <a href="/instrument_admin" class="">Equipment</a>
    </li>
    <li>
    <a href="/project_admin" class="">Project</a>
    </li>
    <li>
    <a href="/profiles" class="">Company Profile</a>
    </li>
    </ul>
    <div class='clear'></div>
    </nav>
    </section>
  </header>
  <div class='clear'></div>